# frontend/Dockerfile.prod
FROM node:20

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./
RUN npm install --omit=dev

COPY frontend /app

RUN npm run build

CMD ["npx", "serve", "-s", "build"]
