version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: janschejbal/raceapp:backend
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/race
      - PYTHONPATH=/app
      - FLASK_ENV=production
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
    image: janschejbal/raceapp:frontend
    ports:
      - "3000:3000"
    restart: always

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: race
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "50000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d race"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
networks:
  internal:
    driver: bridge