version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    networks:
      - app-network
    restart: always
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always
    depends_on:
      - backend

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: race
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
