version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: janschejbal/raceapp:backend
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/race
      - PYTHONPATH=/app
      - FLASK_ENV=production
    network_mode: "host"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: janschejbal/raceapp:frontend
    network_mode: "host"
    depends_on:
      - backend

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: race
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "50001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "10000:8080"
    depends_on:
      - db

volumes:
  pgdata: