# backend/Dockerfile.test
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest pytest-cov pytest-mock

COPY . .

CMD ["python", "-m", "pytest", "--cov=."]