# backend/Dockerfile.dev
FROM python:3.9

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install flask-cors python-dotenv

EXPOSE 5001

CMD ["python", "app.py"]