name: Pylint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run Pylint and Save Report
      id: pylint
      run: |
        SCORE=$(pylint $(git ls-files '*.py') | tee pylint-report.txt | grep "Your code has been rated at" | awk '{print $7}' | cut -d'/' -f1)
        echo "Pylint score: $SCORE"
        echo "score=$SCORE" >> $GITHUB_ENV
    - name: Check Pylint Score
      run: |
        if (( $(echo "$SCORE > 1" | bc -l) )); then
          echo "Pylint score is satisfactory: $SCORE"
        else
          echo "Pylint score is too low: $SCORE"
          exit 1
        fi
      env:
        SCORE: ${{ env.score }}
